[project]
name = "marimo-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "leafmap>=0.57.10",
    "marimo>=0.19.2",
    "pandas>=2.3.3",
    "pymssql>=2.3.11",
    "sqlalchemy>=2.0.45",
]
